source /resources/lab6/load-faculty.sql
source /resources/lab6/load-department.sql
source /resources/lab6/load-worktable_faculty.sql
source /resources/lab6/load-degreeProgram.sql
source /resources/lab6/load-student.sql
source /resources/lab6/load-dDoffers.sql
source /resources/lab6/load-courseDescription.sql
source /resources/lab6/load-courseOffering.sql
source /resources/lab6/load-taken.sql
