
version: '3.8'

services:
  mdb:
    image: mysql:latest
    # image: mysql:5.7
    container_name: mysql
    hostname: mysql
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes: 
      # Where our data will be persisted
      - ./data:/var/lib/mysql
    environment:
      # The default database to be created
      MYSQL_DATABASE: 'tcu'
      # The user that you would like to use to manage the database
      # You don not have to use root, but you can if you like
      MYSQL_USER: 'superfrog'
      # You can use whatever password you like for the user
      MYSQL_PASSWORD: 'password'
      # Password for root 
      MYSQL_ROOT_PASSWORD: 'password'


  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    hostname: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: 'mdb'
      # PMA_USER: 'root'
      PMA_USER: 'superfrog'
      PMA_PASSWORD: 'password'
    restart: unless-stopped


  adminer:
    image: adminer
    container_name: adminer
    depends_on: 
      - 'mdb'
    environment:
      ADMINER_DEFAULT_SERVER: 'mdb'
      ADMINER_DEFAULT_DB_NAME: 'tcu'
      ADMINER_DESIGN: nette
      # ADMINER_DESIGN: galkaev
      ADMINER_PLUGINS: tables-filter tinymce
    ports:
      - 8080:8080
    restart: unless-stopped


  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./workbench:/config
    ports:
      - 3000:3000
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
