
version: '3.8'

services:
  mysql:
    image: mysql:latest
    # image: mysql:5.7
    restart: always
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'superfrog'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./data:/var/lib/mysql


  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./workbench:/config
    ports:
      - 3000:3000
    cap_add:
      - IPC_LOCK
    restart: unless-stopped


  adminer:
    image: adminer
    container_name: adminer
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@eurekalabs.net
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - 8080:8080
    restart: always






