
version: '3.8'

# networks:
#   lab:
#     name: db-network
#     internal: true
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 10.0.103.0/24


services:

# Use postgres/example as user/password credentials
  pgdb:
    # image: postgres:14.2-alpine
    image: postgres:14.2
    container_name: pg-container
    hostname: pgdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/:/var/lib/postgresql/data
    ports:
      - 5432:5432


  pgadmin:
    container_name: pgadmin4-container
    image: dpage/pgadmin4
    hostname: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@db.io
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"


  adminer:
    image: adminer
    container_name: adminer
    depends_on: 
      - 'pgdb'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@eurekalabs.net
      PGADMIN_DEFAULT_PASSWORD: secret
      ADMINER_DEFAULT_SERVER: 'pgdb'
    ports:
      - 8080:8080
    restart: always


# Use different as user/password credentials
  pgdb2:
    image: postgres:14.2-alpine
    container_name: pgdb2
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    volumes:
      - ./data2/:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432




