
version: '3.8'

# networks:
#   lab:
#     name: db-network
#     internal: true
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 10.0.103.0/24


services:

# Use postgres/example as user/password credentials
  db:
    # image: postgres:14.2-alpine
    image: postgres:14.2
    container_name: pg-container
    hostname: pg-server
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: adminer
    environment:
      PGADMIN_DEFAULT_EMAIL: sf@tcu.edu
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - 8080:8080
    restart: always


# Use different as user/password credentials
  db2:
    image: postgres:14.2-alpine
    container_name: pgdb
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    volumes:
      - ./data/:/var/lib/postgresql/data
    ports:
      - 5432:5432

# services:
#   ssh-server:
#     build: ./ssh_server
#     container_name: ssh-server
#     hostname: ssh-server
#     restart: always
#     privileged: true
#     networks:
#       lab:
#         ipv4_address: 10.0.103.2
    # volumes:
    #   - ./ssh_server:/s_keys    


